---
permalink: online-help/reference-cluster-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: 下列欄位可在容量：所有叢集檢視中使用、並可用於自訂檢視和報告中。 
---
= 叢集容量欄位
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
下列欄位可在容量：所有叢集檢視中使用、並可用於自訂檢視和報告中。

* *叢集*
+
叢集名稱。您可以按一下叢集名稱、瀏覽至該叢集的容量詳細資料頁面。

* *叢集FQDN
+
叢集的完整網域名稱（FQDN）。

* * HA配對*
+
透過形成兩個節點所獲得的HA配對值。

* *總原始容量*
+
顯示陣列中所有磁碟的實體容量總計。

* *未設定原始容量*
+
容器類型不是Aggregate、中斷、備援或共享的磁碟未設定容量。此容量一律高於ONTAP 支援的實體磁碟容量。例如、考慮使用2 TB磁碟。磁碟的實體容量ONTAP 為1.6 TB、而Unified Manager中未設定的原始容量則為1.8 TB。

* * Aggregate總容量*
+
使用者可用集合體的總大小。這包括Snapshot複本保留。

* * Aggregate已用容量*
+
已在Aggregate上使用的容量。這包括磁碟區、LUN及其他儲存效率技術經常成本所消耗的容量。

* *彙總未使用的容量*
+
可用於在Aggregate上儲存其他資料的容量。這包括Snapshot複本保留。

* *使用的邏輯空間*
+
儲存在此叢集上所有集合體上的資料實際大小、而不需運用ONTAP 使用NetApp儲存效率技術所節省的成本。

* *資料減量*
+
資料減量比率是根據設定ONTAP 的整套儲存效率設定而定。

* *已分配LUN容量*
+
對應LUN的容量。

* *未分配LUN容量*
+
未對應至主機的所有LUN容量。

* * Volume總容量*
+
磁碟區的總容量（已使用加上未使用）。

* * Volume已用容量*
+
磁碟區的已用容量。

* * Volume未使用的容量*
+
磁碟區未使用的容量。

* * Volume Protection Capacity *
+
已啟用SnapMirror和SnapVault 支援功能的磁碟區容量。

* *使用的雲端層（授權）*
+
雲端層中的資料所使用的空間、是儲存供應商需要FabricPool 使用支援功能的空間。

* *使用的雲端層（其他）*
+
雲端層的資料用於StorageGRID 不ONTAP 需要FabricPool 使用支援的不需要使用支援的不二元化系統和S3傳輸協定儲存區的空間。

* *型號/系列*
+
叢集的模型或系列名稱。

* *作業系統版本*
+
系統上安裝的版本ONTAP 。

* *聯絡人*
+
叢集的聯絡資訊。

* *位置*
+
叢集的位置。


