---
permalink: online-help/reference-volume-thresholds-page.html 
sidebar: sidebar 
keywords:  
summary: 「Volume臨界值」頁面可讓您設定受監控磁碟區的全域健全狀況臨界值。您可以設定個別磁碟區或全域所有磁碟區的臨界值。全域設定選項時、會修改所有物件的預設值。不過、如果物件層級的預設值已變更、則不會修改全域值。 
---
= Volume臨界值頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「Volume臨界值」頁面可讓您設定受監控磁碟區的全域健全狀況臨界值。您可以設定個別磁碟區或全域所有磁碟區的臨界值。全域設定選項時、會修改所有物件的預設值。不過、如果物件層級的預設值已變更、則不會修改全域值。

您必須具有應用程式管理員或儲存管理員角色。

當超過臨界值時、就會產生事件。您可以針對此類事件採取修正行動。

您可以設定下列項目的臨界值：容量、Volume Snapshot複本、qtree配額、Volume成長和inode。



== 容量區域

「容量」區域可讓您設定下列Volume容量臨界值條件。請注意、在磁碟區上啟用「自動擴充」時、容量臨界值會根據自動擴充所設定的最大磁碟區大小而非原始磁碟區大小而被視為違反。

* *空間幾乎已滿*
+
指定一個磁碟區被視為幾乎已滿的百分比：

+
** 預設值：80%
+
此臨界值的值必須低於Volume Full臨界值的值、管理伺服器才能產生事件。

** 產生事件：磁碟區幾乎已滿
** 事件嚴重性：警告


* *空間已滿*
+
指定磁碟區被視為完整磁碟區的百分比：

+
** 預設值：90%
** 產生事件：Volume已滿
** 事件嚴重性：錯誤


* *直到完整日*
+
指定磁碟區達到完整容量之前的剩餘天數：

+
** 預設值：15（這也是最小值）
** 產生的事件：磁碟區天數直到滿為止
** 事件嚴重性：錯誤






== Snapshot複本區域

Snapshot Copies區域可讓您針對Volume中的Snapshot複本設定下列臨界值條件：

* * Snapshot保留已滿*
+
指定保留給Snapshot複本的空間被視為已滿的百分比：

+
** 預設值：90%
** 產生的事件：Volume Snapshot Reserve已滿
** 事件嚴重性：錯誤


* *直到完整日*
+
指定保留給Snapshot複本的空間達到完整容量之前的剩餘天數：

+
** 預設值：7.
** 產生的事件：Volume Snapshot保留天數直到滿為止
** 事件嚴重性：錯誤


* *計數*
+
指定磁碟區上的Snapshot複本數量、這些複本被視為太多：

+
** 預設值：1000
** 產生的事件：快照複本太多
** 事件嚴重性：錯誤Unified Manager觸發事件之前、將每個磁碟區的Snapshot複本數量視為最大值、數量低於ONTAP 「最高值」：




[cols="3*"]
|===
|  | 最多ONTAP | Unified Manager最大化 


 a| 
執行速度為9.3或更早版本的資料、執行速度為9.7或更早版本的資料冊ONTAP FlexGroup ONTAP FlexVol
 a| 
255.
 a| 
250



 a| 
執行速度為9.4或更高的部分、執行速度為9.8或更高版本的部分、以及執行速度為9.8或更高版本的部分ONTAP FlexGroup ONTAP FlexVol
 a| 
1023
 a| 
1000

|===


== qtree配額區域

Qtree配額區域可讓您設定下列Volume配額臨界值條件：

* *幾乎過度使用*
+
指定qtree配額將某個磁碟區視為幾乎過度委派的百分比：

+
** 預設值：95%
** 產生的事件：Volume Qtree配額即將過度使用
** 事件嚴重性：警告


* *過度使用*
+
指定qtree配額將磁碟區視為過度委派的百分比：

+
** 預設值：100%
** 產生的事件：Volume Qtree配額過度使用
** 事件嚴重性：錯誤






== 成長領域

成長區可讓您針對Volume成長設定下列臨界值條件：

* *成長率*
+
指定系統產生Volume成長率異常事件之前、Volume成長率被視為正常的百分比：

+
** 預設值：1%
** 產生的事件：Volume成長率異常
** 事件嚴重性：警告


* *成長率敏感度*
+
指定套用至Volume成長率標準差的因素。如果成長率超過計入的標準差、就會產生Volume成長率異常事件。

+
成長率敏感度的值越低、表示該磁碟區對成長率的變化非常敏感。成長率敏感度的範圍為1到5。

+
** 預設值：2.


+
[NOTE]
====
如果您在全域臨界值層級修改磁碟區的成長率敏感度、則變更也會套用至全域臨界值層級之集合體的成長率敏感度。

====




== inode區域

inode區域可讓您設定下列inode臨界值條件：

* *幾乎已滿*
+
指定一個磁碟區被視為消耗其大部分inode的百分比：

+
** 預設值：80%
** 產生的事件：inode幾乎已滿
** 事件嚴重性：警告


* *完整*
+
指定一個磁碟區被視為已使用其所有inode的百分比：

+
** 預設值：90%
** 產生的事件：inode已滿
** 事件嚴重性：錯誤



