---
permalink: online-help/reference-volume-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: 下列欄位可在容量：All Volumes（所有磁碟區）檢視中使用、並可用於自訂檢視和報告中。 
---
= Volume容量欄位
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
下列欄位可在容量：All Volumes（所有磁碟區）檢視中使用、並可用於自訂檢視和報告中。

* * Volume *
+
Volume名稱。

* *每日成長率%*
+
每24小時在磁碟區內發生的成長率。

* *天滿*
+
Volume達到完整容量之前的預估剩餘天數。

* *可用資料%*
+
磁碟區中可用的資料容量、以百分比表示。

* *可用的資料容量*
+
Volume中的可用資料容量。

* *已用資料%*
+
以百分比表示Volume中已使用的資料。

* *已用資料容量*
+
Volume中使用的資料容量。

* *總資料容量*
+
Volume中的總資料容量（已使用及可用）。

* *使用的邏輯空間*
+
此磁碟區中的資料所使用的邏輯空間、不需運用ONTAP 使用還原儲存效率技術所節省的成本。

* * Snapshot溢位%*
+
Snapshot複本使用的資料空間百分比。

* * Snapshot保留可用%*
+
磁碟區中Snapshot複本可用空間的百分比。

* * Snapshot保留可用容量*
+
磁碟區中Snapshot複本的可用空間量。

* * Snapshot保留已使用%*
+
磁碟區中Snapshot複本使用的空間量、以百分比表示。

* * Snapshot保留已用容量*
+
Volume中Snapshot複本使用的空間量。

* * Snapshot保留總容量*
+
顯示磁碟區中的Snapshot複本總容量。

* *配額已認可容量*
+
保留給磁碟區中配額的空間。

* *配額過度委派容量*
+
系統產生「Volume配額過度使用」事件之前、可用於配額的空間量。

* * inode總數*
+
Volume中的inode數。

* * inode使用率%*
+
磁碟區中使用的inode空間百分比。

* *精簡配置*
+
是否為所選磁碟區設定空間保證。有效值為「是」和「否」

* *空間保證*
+
與磁碟區相關的儲存保證選項。

* *自動擴充*
+
當磁碟區空間不足時、它是否會自動增加大小。

* * Snapshot自動刪除*
+
是否啟用或停用自動刪除Snapshot複本。

* *重複資料刪除*
+
是否為磁碟區啟用或停用重複資料刪除。

* *壓縮*
+
是啟用或停用磁碟區的壓縮。

* *州*
+
正在匯出的Volume狀態。

* *保護角色*
+
為磁碟區設定的保護角色。

* *《類型*》SnapLock
+
Volume是SnapLock 指不屬於SnapLock或不屬於SnapLock Volume的磁碟區。

* *《終止日期*》SnapLock
+
The不再是截止日期SnapLock 。

* *分層政策*
+
為磁碟區設定的分層原則。僅在部署於啟用FabricPool的Aggregate時有效。

* *快取原則*
+
與所選磁碟區相關聯的快取原則。

+
此原則提供有關如何為磁碟區進行Flash Pool快取的資訊。如需快取原則的詳細資訊、請參閱健全狀況：所有磁碟區檢視。

* *快取保留優先順序*
+
用於保留快取集區的優先順序。

* *儲存VM*
+
包含磁碟區的儲存虛擬機器（SVM）名稱。

* *叢集*
+
磁碟區所在的叢集名稱。您可以按一下叢集名稱、瀏覽至該叢集的健全狀況詳細資料頁面。

* *叢集FQDN
+
叢集的完整網域名稱（FQDN）。


