---
section: config
title: 執行組態和管理工作
entries:
- title: 設定Active IQ Unified Manager 功能
  url: "/config/concept-configuring-unified-manager.html"
  entries:
  - title: 組態順序總覽
    url: "/config/concept-overview-of-the-configuration-sequence.html"
  - title: 存取Unified Manager Web UI
    url: "/config/task-accessing-oncommand-unified-manager-web-ui.html"
  - title: 執行Unified Manager Web UI的初始設定
    url: "/config/task-performing-the-initial-setup-of-the-unified-manager-web-ui.html"
  - title: 新增叢集
    url: "/config/task-adding-clusters.html"
  - title: 設定Unified Manager以傳送警示通知
    url: "/config/task-configuring-unified-manager-to-send-alert-notifications.html"
    entries:
    - title: 設定事件通知設定
      url: "/config/task-configuring-event-notification-settings.html"
    - title: 啟用遠端驗證
      url: "/config/task-enabling-remote-authentication.html"
    - title: 從遠端驗證停用巢狀群組
      url: "/config/task-disabling-nested-groups-from-remote-authentication.html"
    - title: 新增驗證伺服器
      url: "/config/task-adding-authentication-servers.html"
    - title: 測試驗證伺服器的組態
      url: "/config/task-testing-the-configuration-of-authentication-servers-um-6-0.html"
    - title: 新增使用者
      url: "/config/task-adding-users.html"
    - title: 新增警示
      url: "/config/task-adding-alerts.html"
  - title: 自動新增至Unified Manager的EMS事件
    url: "/config/reference-ems-events-that-are-added-automatically-to-unified-manager.html"
  - title: 訂閱ONTAP E不到EMS活動
    url: "/config/task-subscribing-to-ontap-ems-events.html"
  - title: 管理SAML驗證設定
    url: "/config/concept-managing-saml-authentication-settings-um.html"
    entries:
    - title: 身分識別供應商要求
      url: "/config/reference-identity-provider-requirements-um.html"
    - title: 啟用SAML驗證
      url: "/config/task-enabling-saml-authentication-um.html"
  - title: 變更本機使用者密碼
    url: "/config/task-changing-the-local-user-password.html"
  - title: 設定工作階段閒置逾時
    url: "/config/task-setting-the-session-inactivity-timeout.html"
  - title: 變更Unified Manager主機名稱
    url: "/config/concept-changing-the-unified-manager-host-name.html"
    entries:
    - title: 變更Unified Manager虛擬應用裝置主機名稱
      url: "/config/task-changing-the-unified-manager-host-name-on-vmware.html"
      entries:
      - title: 產生HTTPS安全性憑證
        url: "/config/task-generating-an-https-security-certificate-ocf.html"
      - title: 重新啟動Unified Manager虛擬機器
        url: "/config/task-restarting-the-unified-manager-virtual-machine.html"
    - title: 變更Linux系統上的Unified Manager主機名稱
      url: "/config/task-changing-the-unified-manager-host-name-on-rhel-or-centos.html"
  - title: 啟用及停用原則型儲存管理
    url: "/config/task-enabling-and-disabling-policy-based-storage-management.html"
- title: 設定Unified Manager備份
  url: "/config/concept-configuring-um-backup.html"
- title: 使用維護主控台
  url: "/config/task-using-the-maintenance-console.html"
  entries:
  - title: 維護主控台提供哪些功能
    url: "/config/concept-what-functionality-the-maintenance-console-provides.html"
  - title: 維護使用者的功能
    url: "/config/concept-what-the-maintenance-user-does.html"
  - title: 診斷使用者功能
    url: "/config/concept-what-the-diagnostic-user-does.html"
  - title: 存取維護主控台
    url: "/config/task-accessing-the-maintenance-console.html"
  - title: 使用vSphere VM主控台存取維護主控台
    url: "/config/task-accessing-the-maintenance-console-using-vsphere.html"
  - title: 維護主控台功能表
    url: "/config/concept-maintenance-console-menu.html"
    entries:
    - title: 網路組態功能表
      url: "/config/reference-network-configuration-menu.html"
    - title: 系統組態功能表
      url: "/config/reference-system-configuration-menu.html"
    - title: 支援與診斷功能表
      url: "/config/reference-support-and-diagnostics-menu.html"
    - title: 其他功能表選項
      url: "/config/reference-additional-menu-options.html"
  - title: 變更Windows上的維護使用者密碼
    url: "/config/task-changing-the-maintenance-user-password-on-windows.html"
  - title: 變更Linux系統上的umadmin密碼
    url: "/config/task-changing-the-umadmin-password-on-rhel.html"
  - title: 變更Unified Manager用於HTTP和HTTPS傳輸協定的連接埠
    url: "/config/task-changing-the-ports-um-uses-for-http-and-https-protocols.html"
  - title: 新增網路介面
    url: "/config/task-adding-additional-network-interfaces.html"
  - title: 將磁碟空間新增至Unified Manager資料庫目錄
    url: "/config/concept-adding-disk-space-to-the-unified-manager-database-directory.html"
    entries:
    - title: 將空間新增至Linux主機的資料目錄
      url: "/config/task-adding-space-to-the-data-directory-of-the-unified-manager-red-hat-enterprise-linux-host.html"
    - title: 為VMware虛擬機器的資料磁碟增加空間
      url: "/config/task-adding-space-to-the-data-disk-of-the-vmware-virtual-machine.html"
    - title: 為Microsoft Windows伺服器的邏輯磁碟機增加空間
      url: "/config/task-adding-space-to-the-data-disk-of-the-microsoft-windows-server.html"
